name: Build

on:
  push:

env:
  # Disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update && sudo apt install -y qemu-kvm
    - run: rustup update
    - run: cargo install bootimage
    - run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
    - run: rustup component add llvm-tools-preview
    - run: cargo test
    - run: cargo bootimage --release
    - name: Release with Notes
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/x86_64-os/release/bootimage-os.bin
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}